### PR TITLE
Various localization fixes and updated Dutch translation

### PR DESCRIPTION
**Pull request by BioMike**
I checked the new wallet and found that the Dutch translation was deeply below standard (I've done software translation in the past for quite a few FOSS projects). While improving the translation I found that the localization files were outdated for all the languages to reflect the current code base. In an attempt to update those I found that the make command for that only updated the English translation file, so I improved that to update ALL the translation files.

This PR contains:
* Fixes to the make files to keep all the translation files updated with respect to the code base (needs to run separate though, not in standard build).
* The updated translation files to reflect the current code base.
* Improved Dutch translation file (not finished yet).

### CODE REVIEW

**Comment by mjmacleod** [comment]
Thanks for this!

Wish you would have contacted me first so we could have saved a bit of work here. Two things.

1) As you may have noticed, we leave 'bitcoin' as is in all the translation files (Same goes for NLG etc.), this is intentional - a system has been introduced that does this in an automated way that makes things easier for us to maintain - and the same would need to be done in your translations, this is not a biggie I can touch it up quickly this side if need be.

2) It would be preferable if you could isolate the guldencoin specific changes to a separate file.
So basically "bitcoin_nl.ts" would remain as is, a new file "guldencoin_nl.ts" should be created and any translations that are different from "bitcoin_nl.ts" should go in this file.
The software will then pick from "guldencoin_nl.ts" when available but otherwise from "bitcoin_nl.ts" - NOTE I still need to write this part so it won't yet work...

I know the above two might seem strange at first, but it is to do with what happens when we merge from upstream in future, I am trying to streamline the process as much as possible so that we can track upstream with much less headaches and keeping changes isolated like this helps a lot in terms of this.
IOW all changes that we make we are trying to think about how best to 'maintain' these changes going forward as well.


Anyway if you can wait a bit I can sort both (1) and (2) out for you, however don't make any more changes in the meantime then... You can carry on with any other changes you want after I've commited guldencoin_nl.ts
Alternatively, you are of course welcome to already move your changes to a guldencoin_nl.ts file in which case go ahead.

**Comment by BioMike** [comment]
Hi MaNI, I'm heading off to work, so I'll keep it short. I assumed the tree was up to date and not much was done since.If you don't mind I would like to sort out (1) and (2) myself as much as possible. I'll see if I can join you on IRC this evening (or maybe this afternoon) to discuss some of the things regarding this.

**Comment by mjmacleod** [comment]
Sounds good.

**Comment by mjmacleod** [comment]
Okay - I've made various changes to the dev branch.
You should be able to work with just these two files now:
https://github.com/nlgcoin/guldencoin-dev/blob/master/src/qt/locale/bitcoin_nl.ts
https://github.com/nlgcoin/guldencoin-dev/blob/master/src/qt/locale/guldencoin_nl.ts

With changes going into the second one - if you use qt-linguist to edit it should let you open both at the same time and view them 'side by side' so that its easier to work.

**Comment by BioMike** [comment]
After discussion with MaNI, I decided to switch to the dev repo and make my changes in there. Closing this now.

**Pull request closed without merging**
